apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zdm.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  ZDM_PRIMARY_CLUSTER: {{ .Values.proxy.primaryCluster | quote }}
  ZDM_READ_MODE: {{ .Values.proxy.readMode | quote }}
  ZDM_LOG_LEVEL: {{ .Values.proxy.logLevel | quote }}
  ZDM_PROXY_MAX_CLIENT_CONNECTIONS: {{ .Values.proxy.maxClientConnections | quote }}
  ZDM_METRICS_ENABLED: {{ .Values.proxy.metricsEnabled | quote }}
