apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zdm.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  ZDM_ORIGIN_PORT: "9042"
  ZDM_TARGET_PORT: "9042"
  ZDM_PRIMARY_CLUSTER: ORIGIN
  ZDM_READ_MODE: PRIMARY_ONLY
  ZDM_LOG_LEVEL: INFO
  ZDM_PROXY_MAX_CLIENT_CONNECTIONS: "1000"
  ZDM_METRICS_ENABLED: "true"
