apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zdm.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  ZDM_PRIMARY_CLUSTER: {{ .Values.proxy.primaryCluster }}
  ZDM_READ_MODE: {{ .Values.proxy.readMode }}
  ZDM_LOG_LEVEL: {{ .Values.proxy.logLevel }}
  ZDM_PROXY_MAX_CLIENT_CONNECTIONS: {{ .Values.proxy.maxClientConnections }}
  ZDM_METRICS_ENABLED: {{ .Values.proxy.metricsEnabled }}
