{{ $zdm_fullname := include "zdm.fullname" . -}}
{{ $zdm_labels := include "zdm.labels" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- if not $.Values.origin.secureBundle }}
  origin_contact_points: {{ join "," $.Values.origin.contactPoints | b64enc }}
  origin_port: {{ $.Values.origin.port | default "9042" | b64enc }}
  {{- end }}
  origin_username: {{ $.Values.origin.username | b64enc }}
  origin_password: {{ $.Values.origin.password | b64enc }}
  {{- if not $.Values.target.secureBundle }}
  target_contact_points: {{ join "," $.Values.target.contactPoints | b64enc }}
  target_port: {{ $.Values.target.port | default "9042" | b64enc }}
  {{- end }}
  target_username: {{ $.Values.target.username | b64enc }}
  target_password: {{ $.Values.target.password | b64enc }}
---

{{- if $.Values.origin.secureBundle }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}-origin-sb
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- (.Files.Glob $.Values.origin.secureBundle).AsSecrets | nindent 2 }}
---
{{- end }}

{{- if $.Values.origin.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}-origin-tls
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- if $.Values.origin.tls.caCert }}
  {{- (.Files.Glob $.Values.origin.tls.caCert).AsSecrets | nindent 2 }}
  {{- end }}
  {{- if $.Values.origin.tls.clientCert }}
  {{- (.Files.Glob $.Values.origin.tls.clientCert).AsSecrets | nindent 2 }}
  {{- end }}
  {{- if $.Values.origin.tls.clientKey }}
  {{- (.Files.Glob $.Values.origin.tls.clientKey).AsSecrets | nindent 2 }}
  {{- end }}
---
{{- end }}

{{- if $.Values.target.secureBundle }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}-target-sb
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- (.Files.Glob $.Values.target.secureBundle).AsSecrets | nindent 2 }}
---
{{- end }}

{{- if $.Values.target.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}-target-tls
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- if $.Values.target.tls.caCert }}
    {{- (.Files.Glob $.Values.target.tls.caCert).AsSecrets | nindent 2 }}
    {{- end }}
    {{- if $.Values.target.tls.clientCert }}
    {{- (.Files.Glob $.Values.target.tls.clientCert).AsSecrets | nindent 2 }}
    {{- end }}
    {{- if $.Values.target.tls.clientKey }}
    {{- (.Files.Glob $.Values.target.tls.clientKey).AsSecrets | nindent 2 }}
    {{- end }}
---
{{- end }}

{{- if $.Values.zdm.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $zdm_fullname }}-tls
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $zdm_labels | nindent 4 }}
type: Opaque
data:
  {{- if $.Values.zdm.tls.caCert }}
    {{- (.Files.Glob $.Values.zdm.tls.caCert).AsSecrets | nindent 2 }}
    {{- end }}
    {{- if $.Values.zdm.tls.serverCert }}
    {{- (.Files.Glob $.Values.zdm.tls.serverCert).AsSecrets | nindent 2 }}
    {{- end }}
    {{- if $.Values.zdm.tls.serverKey }}
    {{- (.Files.Glob $.Values.zdm.tls.serverKey).AsSecrets | nindent 2 }}
    {{- end }}
---
{{- end }}