# pull in these templates outside of range loop
{{ $zdm_fullname := include "zdm.fullname" . -}}
{{- $zdm_labels := include "zdm.labels" . -}}
{{- $zdm_selectorLabels := include "zdm.selectorLabels" . -}}

# calculate a variable that contains all proxy service addresses
{{ $service_addresses := "" -}}
{{- range $index := until (.Values.proxy.count | int) -}}
    {{- $service_addresses = printf "%s,$(%s_%s_SERVICE_HOST)" $service_addresses ($zdm_fullname | upper | replace "-" "_") ($index | toString) -}}
{{- end -}}
{{- $service_addresses = $service_addresses | trimPrefix "," -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- $zdm_labels | nindent 4 }}
    app: {{ $zdm_fullname }}
  name: {{ $zdm_fullname }}
  namespace: {{ $.Values.namespace }}
spec:
  serviceName: {{ $zdm_fullname }}
  replicas: {{ $.Values.proxy.count | int }}
  selector:
    matchLabels:
      {{- $zdm_selectorLabels | nindent 6 }}
      app: {{ $zdm_fullname }}
  template:
    metadata:
      labels:
        {{- $zdm_selectorLabels | nindent 8 }}
        app: {{ $zdm_fullname }}
    spec:
      containers:
      - image: "{{ $.Values.proxy.image.repository }}:{{ $.Values.proxy.image.tag | default $.Chart.AppVersion }}"
        name: {{ $zdm_fullname }}
        command:
        - sh
        - "-c"
        - "ZDM_PROXY_TOPOLOGY_INDEX=`echo ${HOSTNAME##*-}` /main"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: httpproxy
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: httpproxy
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - name: httpproxy
            containerPort: 14001
            protocol: TCP
          - name: cql
            containerPort: 9042
            protocol: TCP
        resources:
          requests:
            memory: {{ $.Values.proxy.resources.requests.memory | quote }}
            cpu: {{ $.Values.proxy.resources.requests.cpu | quote }}
          limits:
            memory: {{ $.Values.proxy.resources.limits.memory | quote }}
            cpu: {{ $.Values.proxy.resources.limits.cpu | quote }}
        env:
        - name: ZDM_PRIMARY_CLUSTER
          value: {{ $.Values.proxy.primaryCluster | upper | quote }}
        - name: ZDM_READ_MODE
          value: {{ $.Values.proxy.readMode | upper | quote }}
        - name: ZDM_LOG_LEVEL
          value: {{ $.Values.proxy.logLevel | upper | quote }}
        - name: ZDM_PROXY_MAX_CLIENT_CONNECTIONS
          value: {{ $.Values.proxy.maxClientConnections | quote }}
        - name: ZDM_METRICS_ENABLED
          value: {{ $.Values.proxy.metricsEnabled | quote }}
        - name: ZDM_PROXY_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZDM_PROXY_LISTEN_PORT
          value: "9042"
        - name: ZDM_METRICS_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZDM_METRICS_PORT
          value: "14001"
        - name: ZDM_PROXY_TOPOLOGY_ADDRESSES
          value: {{ $service_addresses }}
        - name: ZDM_TARGET_SECURE_CONNECT_BUNDLE_PATH
          value: /tmp/scb/target.zip
        - name: ZDM_ORIGIN_CONTACT_POINTS
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: origin_contact_points
        - name: ZDM_ORIGIN_PORT
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: origin_port
        - name: ZDM_ORIGIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: origin_username
        - name: ZDM_ORIGIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: origin_password
        - name: ZDM_TARGET_USERNAME
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: target_username
        - name: ZDM_TARGET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zdmproxy
              key: target_password
        volumeMounts:
        - name: scb
          mountPath: "/tmp/scb"
          readOnly: true
      volumes:
      - name: scb
        secret:
          secretName: zdmproxy-scb
          items:
          - key: secure-connect-target.zip
            path: target.zip
