{
 "title": "ZDM Proxy Dashboard v2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "proxyinstance",
    "query": {
     "query": "{job=~\"zdm_proxy\"}"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "{job=~\"zdm_proxy\"}"
    }
   },
   { "name": "histogram_rate", "label": "Histogram Interval", "query": "1m,2m,3m,4m,5m" },
   { "name": "error_rate", "label": "Error Rate interval", "query": "1m,2m,3m,4m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Proxy level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(zdm_proxy_request_duration_seconds_count{type=~\"reads_origin|reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])",
       "legendFormat": "{type=\"{{type}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Write Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(zdm_proxy_request_duration_seconds_count{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])",
       "legendFormat": "{type=\"{{type}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Read Throughput Aggregate (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(zdm_proxy_request_duration_seconds_count{type=~\"reads_origin|reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Write Throughput Aggregate (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (irate(zdm_proxy_request_duration_seconds_count{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Read Latency by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=~\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p999"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p90"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p95"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p75"
      },
      {
       "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=~\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p999"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p90"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p95"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} {{type}} p75"
      }
     ]
    },
    {
     "title": "Write Latency by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p999"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p90"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p95"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate]))",
       "legendFormat": "{{instance}} writes p75"
      }
     ]
    },
    {
     "title": "Read Latency Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_origin\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_origin p75"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"reads_target\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "reads_target p75"
      }
     ]
    },
    {
     "title": "Write Latency Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\",instance=~\"^($proxyinstance)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_proxy_request_duration_seconds_bucket{type=\"writes\"}[$histogram_rate])) by (le))",
       "legendFormat": "writes p75"
      }
     ]
    },
    {
     "title": "In Flight Read Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (zdm_proxy_inflight_requests_total{type=~\"reads_target|reads_origin\", instance=~\"^($proxyinstance)$\"})"
      }
     ]
    },
    {
     "title": "In Flight Write Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_proxy_inflight_requests_total{type=\"writes\", instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "{instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "In Flight Requests by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (zdm_proxy_inflight_requests_total{type=\"writes\", instance=~\"^($proxyinstance)$\"})",
       "legendFormat": "writes"
      },
      {
       "expr": "sum (zdm_proxy_inflight_requests_total{type=~\"reads_origin|reads_target\", instance=~\"^($proxyinstance)$\"})",
       "legendFormat": "reads"
      }
     ]
    },
    {
     "title": "In Flight Requests by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (zdm_proxy_inflight_requests_total{instance=~\"^($proxyinstance)$\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_client_connections_total{instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "client_connections {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "PS Cache misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_pscache_miss_total{instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "pscache_miss_total {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "PS Cache entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_pscache_entries_total{instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "pscache_entries {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Read Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zdm_proxy_failed_reads_total{instance=~\"^($proxyinstance)$\"}[$error_rate])",
       "legendFormat": "{cluster=\"{{cluster}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}[$error_rate])",
       "legendFormat": "{failed_on=\"{{failed_on}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Read Failure Rate By Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(zdm_proxy_failed_reads_total{instance=~\"^($proxyinstance)$\"}[$error_rate])) by (instance)",
       "legendFormat": "{instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Rate by Cluster",
     "type": "timeseries",
     "description": "Shows failure rate sum by which cluster was reponsible for the failure.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}[$error_rate])) by (failed_on)",
       "legendFormat": "{failed_on=\"{{failed_on}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Rate by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}[$error_rate])) by (instance)",
       "legendFormat": "{instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Read Failure Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_proxy_failed_reads_total{instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "{cluster=\"{{cluster}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}",
       "legendFormat": "{failed_on=\"{{failed_on}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Read Failure Counters By Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (zdm_proxy_failed_reads_total{instance=~\"^($proxyinstance)$\"}) by (instance)",
       "legendFormat": "{instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Counters by Cluster",
     "type": "timeseries",
     "description": "Shows failure rate sum by which cluster was reponsible for the failure.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}) by (failed_on)",
       "legendFormat": "{failed_on=\"{{failed_on}}\"}"
      }
     ]
    },
    {
     "title": "Write Failure Counters by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zdm_proxy_failed_writes_total{instance=~\"^($proxyinstance)$\"}) by (instance)",
       "legendFormat": "{instance=\"{{instance}}\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Origin Read Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(zdm_origin_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",type=\"reads\",node=~\"^($node)$\"}[$histogram_rate])"
      }
     ]
    },
    {
     "title": "Origin Write Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(zdm_origin_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",type=\"writes\",node=~\"^($node)$\"}[$histogram_rate])"
      }
     ]
    },
    {
     "title": "Target Read Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(zdm_target_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",type=\"reads\",node=~\"^($node)$\"}[$histogram_rate])"
      }
     ]
    },
    {
     "title": "Target Write Throughput by Instance (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(zdm_target_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",type=\"writes\",node=~\"^($node)$\"}[$histogram_rate])"
      }
     ]
    },
    {
     "title": "Origin Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
      }
     ]
    },
    {
     "title": "Target Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
      }
     ]
    },
    {
     "title": "Origin Used Stream Ids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_origin_used_stream_ids_total",
       "legendFormat": "{instance={{instance}}, node={{node}}}"
      }
     ]
    },
    {
     "title": "Target Used Stream Ids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_target_used_stream_ids_total",
       "legendFormat": "{instance={{instance}}, node={{node}}}"
      }
     ]
    },
    {
     "title": "Origin Latency Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_origin_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Target Latency Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_target_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Origin Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_origin_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "origin_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Target Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "target_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Origin Connections Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zdm_origin_connections_total{node=~\"^($node)$\"}) by (node)",
       "legendFormat": "origin_connections {node=\"{{node}}\"}"
      },
      {
       "expr": "sum(zdm_origin_connections_total{node=~\"^($node)$\"}) by (instance)",
       "legendFormat": "origin_connections {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Target Connections Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (node)",
       "legendFormat": "target_connections {node=\"{{node}}\"}"
      },
      {
       "expr": "sum(zdm_target_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (instance)",
       "legendFormat": "target_connections {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Origin Error Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Target Error Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Origin Error Rate Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error)(rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (instance) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (node) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Origin Error Rates by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Target Error Rate Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error)(rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (instance) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (node) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Target Error Rates by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Origin Error Rates by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Origin Error Rates by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (rate(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Target Error Rates by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Target Error Rates by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (rate(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Origin Error Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Target Error Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Origin Error Counter Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error)(zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (instance) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (node) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Origin Error Counters by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Target Error Counter Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error)(zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (instance) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (node) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Target Error Counters by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Async Used Stream Ids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_async_used_stream_ids_total",
       "legendFormat": "{instance={{instance}}, node={{node}}}"
      }
     ]
    },
    {
     "title": "Origin Error Counters by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Origin Error Counters by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (zdm_origin_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Target Error Counters by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Target Error Counters by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (zdm_target_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Async Read Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In Flight Async Read Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_async_inflight_requests_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}",
       "legendFormat": "async_inflight_requests {instance=\"{{instance}}\", node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Async Read Throughput (requests per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(zdm_async_request_duration_seconds_count{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])"
      }
     ]
    },
    {
     "title": "Async Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p999"
      },
      {
       "expr": "histogram_quantile(0.95, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p95"
      },
      {
       "expr": "histogram_quantile(0.90, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p90"
      },
      {
       "expr": "histogram_quantile(0.75, rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate]))",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\"} p75"
      }
     ]
    },
    {
     "title": "Async Read Latency Aggregate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(zdm_async_request_duration_seconds_bucket{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$histogram_rate])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Async Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "async_connections {instance=\"{{instance}}\", node=\"{{node}}\"}"
      }
     ]
    },
    {
     "title": "Async Connections Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (node)",
       "legendFormat": "async_connections {node=\"{{node}}\"}"
      },
      {
       "expr": "sum(zdm_async_connections_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}) by (instance)",
       "legendFormat": "async_connections {instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "Async Error Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate])",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Async Error Rate Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (instance) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      },
      {
       "expr": "sum by (node) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Async Error Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}",
       "legendFormat": "{instance=\"{{instance}}\", node=\"{{node}}\", error=\"{{error}}\"}"
      }
     ]
    },
    {
     "title": "Async Error Counter Sums",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (instance) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      },
      {
       "expr": "sum by (node) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Async Error Rates by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Async Error Rates by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Async Error Rates by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (rate(zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"}[$error_rate]))"
      }
     ]
    },
    {
     "title": "Async Error Counters by Instance and Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, node) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Async Error Counters by Instance and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\", node=~\"^($node)$\"})"
      }
     ]
    },
    {
     "title": "Async Error Counters by Node and Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node, error) (zdm_async_requests_failed_total{instance=~\"^($proxyinstance)$\",node=~\"^($node)$\"})"
      }
     ]
    }
   ]
  }
 ]
}