package cloudgateproxy

import (
	"fmt"
	"github.com/datastax/go-cassandra-native-protocol/datacodec"
	"github.com/datastax/go-cassandra-native-protocol/datatype"
	"github.com/datastax/go-cassandra-native-protocol/frame"
	"github.com/datastax/go-cassandra-native-protocol/message"
	"github.com/datastax/go-cassandra-native-protocol/primitive"
)

type ParameterModifier struct {
	timeUuidGenerator TimeUuidGenerator
}

func NewParameterModifier(generator TimeUuidGenerator) *ParameterModifier {
	return &ParameterModifier{timeUuidGenerator: generator}
}

// AddValuesToExecuteFrame generates and adds values for function calls that were replaced in the prior PREPARE message.
//
// These values are added as positional or named depending on whether the frame already has positional
// or named values in the message.
//
// If no values exist in the frame, then this method adds the new values as positional by default
// because they are more efficient.
//
// The *message.Execute object that is returned is the same object that the provided frame contains,
// no new frames or messages are generated by this function.
func (recv *ParameterModifier) AddValuesToExecuteFrame(
	newFrame *frame.Frame, preparedStmtInfo *PreparedStatementInfo,
	variablesMetadata *message.VariablesMetadata) (*message.Execute, error) {
	newExecuteMsg, ok := newFrame.Body.Message.(*message.Execute)
	if !ok {
		return nil, fmt.Errorf("expected Execute but got %v instead", newFrame.Body.Message.GetOpCode())
	}

	if len(preparedStmtInfo.GetReplacedTerms()) > 0 {
		err := recv.addValuesToExecuteMessage(newFrame.Header.Version, newExecuteMsg, preparedStmtInfo, variablesMetadata)
		if err != nil {
			return nil, err
		}
	}

	return newExecuteMsg, nil
}

func (recv *ParameterModifier) addValuesToExecuteMessage(
	version primitive.ProtocolVersion, executeMsg *message.Execute,
	preparedStmtInfo *PreparedStatementInfo, variablesMetadata *message.VariablesMetadata) error {
	if executeMsg.Options == nil {
		executeMsg.Options = &message.QueryOptions{}
	}

	var err error
	if len(executeMsg.Options.NamedValues) == 0 {
		if preparedStmtInfo.ContainsPositionalMarkers() {
			err = recv.addPositionalValuesForReplacedPositionalMarkers(
				version, executeMsg, preparedStmtInfo.GetReplacedTerms(), variablesMetadata)
		} else {
			err = recv.addPositionalValuesForReplacedNamedMarkers(version, executeMsg, variablesMetadata)
		}
	} else {
		err = recv.addNamedValuesForReplacedNamedMarkers(version, executeMsg, variablesMetadata)
	}

	return err
}

func (recv *ParameterModifier) addPositionalValuesForReplacedPositionalMarkers(version primitive.ProtocolVersion,
	executeMsg *message.Execute, replacedTerms []*term, variablesMetadata *message.VariablesMetadata) error {
	newPositionalValues := make([]*primitive.Value, 0, len(executeMsg.Options.PositionalValues)+len(replacedTerms))
	start := 0
	offset := 0
	var generatedTimeUuidValue *primitive.Value
	var err error
	for _, currentTerm := range replacedTerms {
		newValueIdx := offset + currentTerm.previousPositionalIndex + 1
		if currentTerm.previousPositionalIndex >= len(executeMsg.Options.PositionalValues) {
			return fmt.Errorf("invalid number of positional values in execute %v", executeMsg)
		}

		if currentTerm.previousPositionalIndex >= 0 {
			end := currentTerm.previousPositionalIndex + 1
			newPositionalValues = append(
				newPositionalValues,
				executeMsg.Options.PositionalValues[start:end]...)
			start = end
		}

		if currentTerm.isFunctionCall() && currentTerm.functionCall.isNow() {
			if newValueIdx >= len(variablesMetadata.Columns) {
				return fmt.Errorf("could not insert positional value because columns metadata has unexpected length; "+
					"execute: %v variablesmetadata: %v", executeMsg, variablesMetadata)
			}

			if generatedTimeUuidValue == nil {
				generatedTimeUuidValue, err = recv.generateTimeUuidValue(version, variablesMetadata.Columns[newValueIdx].Type)
				if err != nil {
					return fmt.Errorf("could not generate new timeuuid value: %w", err)
				}
			}

			newPositionalValues = append(newPositionalValues, generatedTimeUuidValue)
			offset++
		}
	}

	if start < len(executeMsg.Options.PositionalValues) {
		newPositionalValues = append(
			newPositionalValues,
			executeMsg.Options.PositionalValues[start:]...)
	}
	executeMsg.Options.PositionalValues = newPositionalValues

	return nil
}

func (recv *ParameterModifier) addPositionalValuesForReplacedNamedMarkers(version primitive.ProtocolVersion,
	executeMsg *message.Execute, variablesMetadata *message.VariablesMetadata) error {
	colLength := len(variablesMetadata.Columns)
	originalPositionalValuesLength := len(executeMsg.Options.PositionalValues)
	newPositionalValues := make([]*primitive.Value, 0, colLength)

	var generatedTimeUuidValue *primitive.Value
	var err error
	currentIdx := 0
	for _, col := range variablesMetadata.Columns {
		replaced := false
		if col.Name != "" {
			switch col.Name {
			case cloudgateNowNamedMarker:
				if generatedTimeUuidValue == nil {
					generatedTimeUuidValue, err = recv.generateTimeUuidValue(version, col.Type)
					if err != nil {
						return fmt.Errorf("could not generate new timeuuid value: %w", err)
					}
				}
				newPositionalValues = append(newPositionalValues, generatedTimeUuidValue)
				replaced = true
			default:
			}
		}

		if !replaced {
			if currentIdx >= originalPositionalValuesLength {
				return fmt.Errorf("invalid index (%v) while copying positional values: %v", currentIdx, originalPositionalValuesLength)
			}
			newPositionalValues = append(newPositionalValues, executeMsg.Options.PositionalValues[currentIdx])
			currentIdx++
		}
	}

	executeMsg.Options.PositionalValues = newPositionalValues
	return nil
}

func (recv *ParameterModifier) addNamedValuesForReplacedNamedMarkers(version primitive.ProtocolVersion,
	executeMsg *message.Execute, variablesMetadata *message.VariablesMetadata) error {
	if executeMsg.Options.NamedValues == nil {
		executeMsg.Options.NamedValues = make(map[string]*primitive.Value, len(variablesMetadata.Columns))
	}

	var generatedTimeUuidValue *primitive.Value
	var err error
	for _, col := range variablesMetadata.Columns {
		if col.Name != "" {
			_, exists := executeMsg.Options.NamedValues[col.Name]
			if exists {
				continue
			}

			switch col.Name {
			case cloudgateNowNamedMarker:
				if generatedTimeUuidValue == nil {
					generatedTimeUuidValue, err = recv.generateTimeUuidValue(version, col.Type)
					if err != nil {
						return err
					}
				}
				executeMsg.Options.NamedValues[cloudgateNowNamedMarker] = generatedTimeUuidValue
			default:
				return fmt.Errorf("could not generate value for column %v", col.Name)
			}
		}
	}

	return nil
}

func (recv *ParameterModifier) generateTimeUuidValue(
	version primitive.ProtocolVersion, valueType datatype.DataType) (*primitive.Value, error) {
	generatedTimeUuid := recv.timeUuidGenerator.GetTimeUuid()
	newValueCodec, err := datacodec.NewCodec(valueType)
	if err != nil {
		return nil, fmt.Errorf("could not create codec for new timeuuid value: %w", err)
	}

	generatedTimeUuidPrimitive := primitive.UUID(generatedTimeUuid)
	generatedTimeUuidValue, err := newValueCodec.Encode(&generatedTimeUuidPrimitive, version)
	if err != nil {
		return nil, fmt.Errorf("could not encode new timeuuid value: %w", err)
	}

	return primitive.NewValue(generatedTimeUuidValue), nil
}
