kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: zdm-proxy
apiVersion: v1
data:
  ZDM-Prometheus.yaml: |+
    apiVersion: 1

    deleteDatasources:
     - name: "Prometheus"

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      version: 1
      editable: true
