apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: zdm-proxy
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    name: prometheus
  selector:
    app: prometheus