apiVersion: v1
data:
  ORIGIN_PASSWORD: ZS15Qy1RVFBLcFp3VV9lS01zMFBvdXgrOEE5SS1kYTBMUWlQTWZCQmdLLVJHYXRDY01UOUN6M3RIMl9RZmNjSVc3U3QrVVpDOEF3MFp0c1k2YTEsSGYzNGlLOHhaS181QlMrWmpnZ3JpMGYxTFo0bGNNUGUyWm5BLmkwbXFwQkQ=
  ORIGIN_USERNAME: aUpMcHRzV3V4alpEaWhrSGJsTVFaWVJw
  TARGET_PASSWORD: ZS15Qy1RVFBLcFp3VV9lS01zMFBvdXgrOEE5SS1kYTBMUWlQTWZCQmdLLVJHYXRDY01UOUN6M3RIMl9RZmNjSVc3U3QrVVpDOEF3MFp0c1k2YTEsSGYzNGlLOHhaS181QlMrWmpnZ3JpMGYxTFo0bGNNUGUyWm5BLmkwbXFwQkQ=
  TARGET_USERNAME: aUpMcHRzV3V4alpEaWhrSGJsTVFaWVJw
kind: Secret
metadata:
  name: zdmproxy
  namespace: zdmproxy
