apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zdm-proxy-0
    role: zdm-proxy
  name: zdm-proxy-0
  namespace: zdmproxy
spec:
  ports:
  - name: 9042-9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: zdm-proxy-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zdm-proxy-1
    role: zdm-proxy
  name: zdm-proxy-1
  namespace: zdmproxy
spec:
  ports:
  - name: 9042-9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: zdm-proxy-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zdm-proxy-2
    role: zdm-proxy
  name: zdm-proxy-2
  namespace: zdmproxy
spec:
  ports:
  - name: 9042-9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: zdm-proxy-2
  type: ClusterIP
