name: Release Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

env:
  BINARY_PREFIX: axonops-zdm-proxy

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    container: golang:1.24.2-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # workaround for issue: https://github.com/docker-library/golang/issues/452#issuecomment-1418939909
      - name: Set workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Build Linux/amd64 binary
        run: |
          export GO111MODULE=on
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=amd64
          go build -o ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} ./proxy
          tar cvfz ${{ env.BINARY_PREFIX }}-linux-amd64-${{ github.ref_name }}.tgz ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} LICENSE
      - name: Build Windows/amd64 binary
        run: |
          apt update
          apt -y install zip
          export GO111MODULE=on
          export CGO_ENABLED=0
          export GOOS=windows
          export GOARCH=amd64
          go build -o ${{ env.BINARY_PREFIX }}-${{ github.ref_name }}.exe ./proxy
          zip -vr ${{ env.BINARY_PREFIX }}-windows-amd64-${{ github.ref_name }}.zip ${{ env.BINARY_PREFIX }}-${{ github.ref_name }}.exe LICENSE
      - name: Build Darwin/amd64 binary
        run: |
          export GO111MODULE=on
          export CGO_ENABLED=0
          export GOOS=darwin
          export GOARCH=amd64
          go build -o ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} ./proxy
          tar cvfz ${{ env.BINARY_PREFIX }}-darwin-amd64-${{ github.ref_name }}.tgz ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} LICENSE
      - name: Build Darwin/arm64 binary
        run: |
          export GO111MODULE=on
          export CGO_ENABLED=0
          export GOOS=darwin
          export GOARCH=arm64
          go build -o ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} ./proxy
          tar cvfz ${{ env.BINARY_PREFIX }}-darwin-arm64-${{ github.ref_name }}.tgz ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} LICENSE
      - name: Build Linux/arm64 binary
        run: |
          export GO111MODULE=on
          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=arm64
          go build -o ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} ./proxy
          tar cvfz ${{ env.BINARY_PREFIX }}-linux-arm64-${{ github.ref_name }}.tgz ${{ env.BINARY_PREFIX }}-${{ github.ref_name }} LICENSE
      - name: Generate Checksums
        run: |
          sha256sum ${{ env.BINARY_PREFIX }}-linux-amd64-${{ github.ref_name }}.tgz | cut -d ' ' -f 1 > ${{ env.BINARY_PREFIX }}-linux-amd64-${{ github.ref_name }}-sha256.txt
          sha256sum ${{ env.BINARY_PREFIX }}-windows-amd64-${{ github.ref_name }}.zip | cut -d ' ' -f 1 > ${{ env.BINARY_PREFIX }}-windows-amd64-${{ github.ref_name }}-sha256.txt
          sha256sum ${{ env.BINARY_PREFIX }}-darwin-amd64-${{ github.ref_name }}.tgz | cut -d ' ' -f 1 > ${{ env.BINARY_PREFIX }}-darwin-amd64-${{ github.ref_name }}-sha256.txt
          sha256sum ${{ env.BINARY_PREFIX }}-darwin-arm64-${{ github.ref_name }}.tgz | cut -d ' ' -f 1 > ${{ env.BINARY_PREFIX }}-darwin-arm64-${{ github.ref_name }}-sha256.txt
          sha256sum ${{ env.BINARY_PREFIX }}-linux-arm64-${{ github.ref_name }}.tgz | cut -d ' ' -f 1 > ${{ env.BINARY_PREFIX }}-linux-arm64-${{ github.ref_name }}-sha256.txt
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: AxonOps ZDM Proxy ${{ github.ref_name }}
          files: |
            ${{ env.BINARY_PREFIX }}-linux-amd64-${{ github.ref_name }}.tgz
            ${{ env.BINARY_PREFIX }}-linux-amd64-${{ github.ref_name }}-sha256.txt
            ${{ env.BINARY_PREFIX }}-windows-amd64-${{ github.ref_name }}.zip
            ${{ env.BINARY_PREFIX }}-windows-amd64-${{ github.ref_name }}-sha256.txt
            ${{ env.BINARY_PREFIX }}-darwin-amd64-${{ github.ref_name }}.tgz
            ${{ env.BINARY_PREFIX }}-darwin-amd64-${{ github.ref_name }}-sha256.txt
            ${{ env.BINARY_PREFIX }}-darwin-arm64-${{ github.ref_name }}.tgz
            ${{ env.BINARY_PREFIX }}-darwin-arm64-${{ github.ref_name }}-sha256.txt
            ${{ env.BINARY_PREFIX }}-linux-arm64-${{ github.ref_name }}.tgz
            ${{ env.BINARY_PREFIX }}-linux-arm64-${{ github.ref_name }}-sha256.txt
